services:
  - type: web
    name: claude-clone-backend
    env: docker
    buildCommand: docker build -t claude-clone-backend .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: MODEL_ID
        value: facebook/blenderbot-400M-distill 